[build]
builder = "nixpacks"
buildCommand = "bundle install"

[deploy]
startCommand = "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p ${PORT:-3001}"
healthcheckPath = "/api/v1/cars"
healthcheckTimeout = 100

[services.worker]
startCommand = "bundle exec rake solid_queue:start"