---
openapi: 3.0.1
info:
  title: El Dorado API V1
  version: v1
  description: API for El Dorado Car Reservations - Built with Rails & JWT
servers:
- url: http://localhost:3001
  description: Local Development Server
- url: https://{defaultHost}
  description: Production Server
  variables:
    defaultHost:
      default: eldorado.up.railway.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter your JWT token (e.g., eyJhbGciOiJIUzI1...)
  schemas:
    reservation:
      type: object
      properties:
        id:
          type: integer
        pickup_date:
          type: string
          format: date-time
        dropoff_date:
          type: string
          format: date-time
        car:
          "$ref": "#/components/schemas/car"
      required:
      - id
      - pickup_date
      - dropoff_date
      - car
    reservation_request:
      type: object
      properties:
        car_id:
          type: integer
          example: 1
        pickup_date:
          type: string
          format: date-time
          example: '2026-04-01T10:00:00Z'
        dropoff_date:
          type: string
          format: date-time
          example: '2026-04-05T10:00:00Z'
      required:
      - car_id
      - pickup_date
      - dropoff_date
    reservation_single_response:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
          example: Success
        data:
          type: object
          properties:
            id:
              type: integer
            pickup_date:
              type: string
              format: date-time
            dropoff_date:
              type: string
              format: date-time
            car:
              "$ref": "#/components/schemas/car"
          required:
          - id
          - pickup_date
          - dropoff_date
          - car
      required:
      - status
      - message
      - data
    reservation_collection_response:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
          example: Reservations retrieved
        data:
          type: array
          items:
            "$ref": "#/components/schemas/reservation"
      required:
      - status
      - message
      - data
    car:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image:
          type: string
        model:
          type: string
          example: 2022 SV
        daily_price:
          type: string
          example: '1000.0'
        description:
          type: string
        status:
          type: string
          example: available
      required:
      - name
      - image
      - model
      - daily_price
      - description
      - status
    car_request:
      type: object
      properties:
        name:
          type: string
          example: Tesla Model 3
        image:
          type: string
          example: https://example.com/car.jpg
        model:
          type: string
          example: 2024 Performance
        daily_price:
          type: number
          example: 150.0
        description:
          type: string
          example: All-electric sedan with Autopilot.
      required:
      - name
      - image
      - model
      - daily_price
    car_single_response:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        data:
          "$ref": "#/components/schemas/car"
      required:
      - status
      - message
      - data
    car_collection_response:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        data:
          type: array
          items:
            "$ref": "#/components/schemas/car"
      required:
      - status
      - message
      - data
    car_status_history_response:
      type: object
      properties:
        id:
          type: integer
        from_status:
          type: string
        to_status:
          type: string
        notes:
          type: text
        created_at:
          type: string
          format: date-time
        user_details:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            email:
              type: string
        car_details:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            model:
              type: string
      required:
      - id
      - from_status
      - to_status
      - notes
      - created_at
      - user_details
      - car_details
    car_status_history_collection_response:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
        data:
          type: array
          items:
            "$ref": "#/components/schemas/car_status_history_response"
      required:
      - status
      - message
      - data
    user_login_request:
      type: object
      properties:
        email:
          type: string
          example: cassius@rebel.org
        password:
          type: string
          format: password
          example: password123
      required:
      - email
      - password
    user_registration_request:
      type: object
      properties:
        name:
          type: string
          example: Cassius Andor
        email:
          type: string
          example: cassius@rebel.org
        password:
          type: string
          format: password
          example: password123
        password_confirmation:
          type: string
          format: password
          example: password123
      required:
      - name
      - email
      - password
      - password_confirmation
    user_response:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
        data:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            email:
              type: string
            role:
              type: string
              example: admin
          required:
          - id
          - name
          - email
    error:
      type: object
      properties:
        code:
          type: integer
          example: 401
        message:
          type: string
          example: Invalid credentials
      required:
      - code
      - message
paths:
  "/api/v1/admin/cars/{car_id}/status_histories":
    parameters:
    - name: car_id
      in: path
      description: ID of the car to view history for
      required: true
      schema:
        type: integer
    get:
      summary: Retrieve Car Maintenance History (Admin Only)
      tags:
      - Admin/Audit Logs
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Logs retrieved successfully
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/car_status_history_collection_response"
        '403':
          description: Forbidden - User is not an admin
        '404':
          description: Car not found
  "/api/v1/admin/cars":
    get:
      summary: List all Cars (Admin Only)
      tags:
      - Admin/Cars
      security:
      - bearerAuth: []
      responses:
        '200':
          description: All cars retrieved
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/car_collection_response"
        '403':
          description: Forbidden - Not an Admin
    post:
      summary: Create a New Car
      tags:
      - Admin/Cars
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Car created successfully
        '422':
          description: Validation failed
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/car_request"
  "/api/v1/admin/cars/{id}":
    parameters:
    - name: id
      in: path
      description: Car ID
      required: true
      schema:
        type: integer
    patch:
      summary: Update a Car
      tags:
      - Admin/Cars
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Car updated successfully
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/car"
  "/api/v1/admin/cars/{id}/availability":
    parameters:
    - name: id
      in: path
      description: Car ID
      required: true
      schema:
        type: integer
    patch:
      summary: Toggle Car Availability
      tags:
      - Admin/Cars
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Status toggled successfully
        '409':
          description: Conflict - Car is currently reserved
  "/api/v1/auth/register":
    post:
      summary: User Registration
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: User registered successfully
          headers:
            Authorization:
              type: string
              description: JWT Bearer Token
        '422':
          description: Validation Error
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/user_registration_request"
  "/api/v1/auth/login":
    post:
      summary: Sign in User
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User logged in successfully
          headers:
            Authorization:
              type: string
              description: JWT Bearer Token
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/user_login_request"
  "/api/v1/auth/logout":
    delete:
      summary: Sign out User
      tags:
      - Authentication
      security:
      - bearerAuth: []
      responses:
        '200':
          description: User logged out successfully
  "/api/v1/cars":
    get:
      summary: List all Cars
      tags:
      - Cars
      responses:
        '200':
          description: List of available cars found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/car_collection_response"
  "/api/v1/cars/{id}":
    parameters:
    - name: id
      in: path
      description: Car ID
      required: true
      schema:
        type: integer
    get:
      summary: Get Specific Car
      tags:
      - Cars
      responses:
        '200':
          description: Single Car found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/car_single_response"
        '404':
          description: Car not found
  "/api/v1/reservations":
    get:
      summary: Get user car reservations
      tags:
      - Reservations
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Reservations retrieved
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/reservation_collection_response"
    post:
      summary: Reserve A Car
      tags:
      - Reservations
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Reservation created successfully
        '422':
          description: Validation failed
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/reservation_request"
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: Reservation ID
      required: true
      schema:
        type: integer
    delete:
      summary: Delete a car reservation
      tags:
      - Reservations
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Reservation deleted successfully
        '404':
          description: Reservation not found
  "/api/v1/profile":
    get:
      summary: Show Current User Profile
      tags:
      - User Profile
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_response"
        '401':
          description: Unauthorized - Please login
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
